### ISSUE TITLE
Combine dmd and binutils and gdb + git build scripts

### ISSUE THREAD

**Issue by ghost** [PowerNex/powernex-dmd#1]
Git has an option to pull a specific tag.
I suggest we combine the `dmd`, `binutils` and `gdb` parts. Making a build script that allows cloning the `dmd-<VERSION>` Git commit, patching it, and compiling it automagically. For `binutils` and `gdb`, offer two options: A default of downloading the presetup `tar.gz`s and compiling, or using a specific Git revision.
We could make the script in two ways: D, or Bash. Both have the necessary tools. Using D will ensure that the end user _has_ a valid D compiler. Using Bash would force the compilable OSs into mostly Linux variants.

**Comment by Vild** [comment]
I have all the different toolchain parts separated because I have setup so [Jenkins](https://ci.vild.io/blue/organizations/jenkins/pipelines) compiles each part, and then `toolchainmanager.d` will check using the Jenkins api if there is a newer toolchain version to download and what the link is to download the latest version from.

I could add the ability for `toolchainManager.d` to clone and build the different parts, that isn't a bad idea.
